sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - nvm install 9
  - npm install --global mocha
  - pip install flake8
script:
  - flake8 --ignore=E501 app/
  - python manage.py test -v2 app
  - mocha app/static/test/
